use_frameworks!



target 'StarMessenger_Example' do
  pod 'StarMessenger', :path => '../'
  pod 'FLAnimatedImage'

  target 'StarMessenger_Tests' do
    inherit! :search_paths

    
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        end
    end
end
