use_frameworks!

target 'StarMessenger_Example' do
  pod 'StarMessenger', :path => '../'

  target 'StarMessenger_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
